### ISSUE TITLE
error in starting vagrant

### ISSUE THREAD

**Issue by lcerrato** [Capitains/vagrant-capitains-dev#3]
worked fine Wednesday and doesn't want to start now 

here is the error:

Traceback (most recent call last):
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/flask-capitains-nemo/flask_nemo/__init__.py", line 633, in <lambda>
    return lambda **kwargs: self.route(getattr(self, name), **kwargs)
  File "/home/vagrant/flask-capitains-nemo/flask_nemo/__init__.py", line 720, in route
    return self.render(**new_kwargs)
  File "/home/vagrant/flask-capitains-nemo/flask_nemo/__init__.py", line 645, in render
    kwargs["collections"] = self.get_collections()
  File "/home/vagrant/flask-capitains-nemo/flask_nemo/__init__.py", line 303, in get_collections
    inventory = self.get_inventory()
  File "/home/vagrant/flask-capitains-nemo/flask_nemo/__init__.py", line 293, in get_inventory
    inventory = MyCapytain.resources.inventory.TextInventory(resource=reply)
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/MyCapytain-0.1.0-py3.4.egg/MyCapytain/resources/inventory.py", line 447, in __init__
    super(TextInventory, self).__init__(**kwargs)
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/MyCapytain-0.1.0-py3.4.egg/MyCapytain/resources/proto/inventory.py", line 286, in __init__
    self.setResource(resource)
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/MyCapytain-0.1.0-py3.4.egg/MyCapytain/resources/proto/inventory.py", line 101, in setResource
    self.parse(resource)
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/MyCapytain-0.1.0-py3.4.egg/MyCapytain/resources/inventory.py", line 482, in parse
    self.xml = xmlparser(resource)
  File "/home/vagrant/flask-capitains-nemo/venv/lib/python3.4/site-packages/MyCapytain-0.1.0-py3.4.egg/MyCapytain/common/utils.py", line 61, in xmlparser
    parsed = etree.parse(xml).getroot()
  File "lxml.etree.pyx", line 3310, in lxml.etree.parse (src/lxml/lxml.etree.c:72517)
    
  File "parser.pxi", line 1808, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:106174)
    
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106403)
    
  File "parser.pxi", line 1709, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105106)
    
  File "parser.pxi", line 1047, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:99534)
    
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
    
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
    
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94853)
    
File "<string>", line None
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 53, column 16245

**Comment by lcerrato** [comment]
just ran --provision and it worked
